### ISSUE TITLE
missing dependency pyodbc

### ISSUE THREAD

**Issue by bandrel** [quentinhardy/msdat#1]
The documentation fails to mention that you need to do `sudo pip install pyodbc`

**Comment by quentinhardy** [comment]
Thanks. 
It was a bug in _Mssql.py_. 
Pyodbc import is not required anymore because Pyodbc is not used.
Pymssql is used in MSDAT. 
See: https://github.com/quentinhardy/msdat/commit/da5430e875f7cc5a0548f8ea9a47670be1020df5
