### ISSUE TITLE
No module named pymssql

### ISSUE THREAD

**Issue by stack00** [quentinhardy/msdat#6]
hi there, could you please help me with this
root@kali:~/Downloads/mssql/msdat# ./msdat.py -h
Traceback (most recent call last):
  File "./msdat.py", line 10, in <module>
    from Mssql import Mssql
  File "/root/Downloads/mssql/msdat/Mssql.py", line 6, in <module>
    import pymssql, _mssql, decimal
ImportError: No module named pymssql
root@kali:~/Downloads/mssql/msdat# pip3 install pymssql
Requirement already satisfied: pymssql in /usr/local/lib/python3.8/dist-packages (2.1.5)

**Comment by quentinhardy** [comment]
Do you have still the error ? Do you have more details ?

**Comment by zAbuQasem** [comment]
Just run it with python3 and everything will be fine.
`python3 msdat.py`

**Comment by Zamanry** [comment]
I had the same issue. Python and Python3 (which are both Python3.9.10) failed. Machine is up-to-date.

![image](https://user-images.githubusercontent.com/28152647/157756113-e00e966b-8cbf-4a40-b8eb-920d5be6d851.png)

**Comment by zAbuQasem** [comment]
Try running the tool with sudo

**Comment by Zamanry** [comment]
Darn

![image](https://user-images.githubusercontent.com/28152647/157757910-b5e76677-4072-465e-923b-6e0f699c8d8e.png)

**Comment by ecofintech** [comment]
Solved using virtualenv python3.10 and modifiying:
`Mssql.py` line 6 `import pymssql, pymssql._mssql, decima
`

**Comment by quentinhardy** [comment]
thx
