### ISSUE TITLE
Multiple Server Support

### ISSUE THREAD

**Issue by Zamanry** [quentinhardy/msdat#7]
It would be cool if we added a flag such as `-sL` to run the intended module(s) against multiple servers at once. I am already wrapping msdat in a Bash script. This would be a line delimited text file of servers rather than a nmap input file.

I see that multiple hosts are supported for password guessing:
```
PPpassguesser.add_argument('-l', dest='hostlist', required=False, help='filename which contains hosts (one ip on each line: "ip:port" or "ip" only)')
```

**Comment by quentinhardy** [comment]
Good idea

**Comment by quentinhardy** [comment]
Implemented  for _all_ and _passwordguesser_ modules
